### ISSUE TITLE
Update Homebrew Cask URL

### ISSUE THREAD

**Issue by reitermarkus** [mcnamaram/dotfiles#1]
Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`README.md`](https://github.com/mcnamaram/dotfiles/blob/47c91d8b8a9fc941f125517c48f238d41d903fb1/README.md). This domain expired a few years ago and is not controlled by Homebrew anymore.

When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.

Thank you,
the Homebrew team.

**Comment by mcnamaram** [comment]
updated to the second one.  thanks!
